# GeoNetwork-UI configuration
# Note: this file's syntax is TOML (https://toml.io/)

### GLOBAL SETTINGS

[global]
# This URL (relative or absolute) must point to the API endpoint of a GeoNetwork4 instance
geonetwork4_api_url = "/geonetwork/srv/api"
# This should point to a proxy to avoid CORS errors on some requests (data preview, OGC capabilities etc.)
# The actual URL will be appended after this path, e.g. : https://my.proxy/?url=http%3A%2F%2Fencoded.url%2Fows`
# This is an optional parameter: leave empty to disable proxy usage
proxy_path = ""

### MAP SETTINGS
# The map section allows to override default settings of the map view.
# Example:
#
[map]
# max_zoom = 10
# max_extent = [-418263.418776, 5251529.591305, 961272.067714, 6706890.609855]
# use_basemap_from_layers = false
# 
# Layers (basemaps, overlays, masks) can be added to the map view with three properties:
# - type (mandatory): Indicates the layer type. Possible values are 'xyz', 'wms', 'wfs'.
# - url (mandatory): Layer endpoint URL.
# - name: Mandatory for 'wms', 'wfs' types where it indicates the layer name.
# Layer order in the config is the same as in the map, the first one being the bottom one.
# If you want to override the default basemap with the first layer of your config set use_basemap_from_layers = true (default: false)
# Each layer is defined in its own [[layers]] section.
# Example:
# [[layers]]
# type = "xyz"
# url = "https://{a-c}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
# [[layers]]
# type = "wfs"
# url = "https://www.geo2france.fr/geoserver/cr_hdf/ows"
# name = "masque_hdf_ign_carto_latin1"
#

### VISUAL THEME

# All parameters are expressed in CSS format, see:
#  - for color: https://developer.mozilla.org/en-US/docs/Web/CSS/color
#  - for font families: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
[theme]
primary_color = "#0f4395"
secondary_color = "#8bc832"
main_color = "#212029" # All-purpose text color
background_color = "#fdfbff"
# main_font = "'My Custom Font', fallback-font"
# title_font = "'My Custom Title Font', fallback-font-title"
# fonts_stylesheet_url = "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Permanent+Marker&display=swap"

### TRANSLATIONS

# To override translations in a specific language, use a 'translations.xx' section where 'xx' is a language code.
# Language codes are expressed in ISO 639-1 codes, see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Example:
#
# [translations.en]
# results.sortBy.dateStamp = "Last time someone changed something"
# [translations.fr]
# results.sortBy.dateStamp = "Dernière fois que quelqu'un a modifié quelque chose"
#
# Note:
#   translation keys ending with ".html" _can_ contain HTML markup, including inline CSS:
#     catalog.welcome.html = """
#     Welcome to <span class="text-primary">Organization</span>'s<br>
#     wonderful <span style="font-size: 1.2em;">data catalogue</span>
#     """

[translations.en]
datahub.header.title.html = '<div class="text-white">Toutes les <span class="text-primary">données<br>publiques</span> de mon organisation</div>'
