# Common configuration for all GeoNetwork-UI applications
# Note: this file's syntax is TOML (https://toml.io/)

[global]
# This URL (relative or absolute) must point to the API endpoint of a GeoNetwork4 instance
geonetwork4_api_url = "/geonetwork/srv/api"
# This should point to a proxy to avoid CORS errors on some requests (data preview, OGC capabilities etc.)
# The actual URL will be appended after this path, e.g. : https://my.proxy/?url=http%3A%2F%2Fencoded.url%2Fows`
# This is an optional parameter: leave empty to disable proxy usage
proxy_path = ""

# Theme parameters, used to customize appearance
# All parameters are expressed in CSS format, see:
#  - for color: https://developer.mozilla.org/en-US/docs/Web/CSS/color
#  - for font families: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
[theme]
primary_color = "#093564"
secondary_color = "#c2e9dc"
main_color = "#212029" # All-purpose text color
background_color = "#fdfbff"
# custom fonts are optional
#main_font = "My Custom Font", fallback-font
#title_font = "My Custom Title Font", fallback-font-title

# To override translations in a specific language, use a 'translations.xx' section where 'xx' is a language code.
# Language codes are expressed in ISO 639-1 codes, see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
#
# Example:
# [translations.en]
# "results.sortBy.dateStamp" = "Last time someone changed something"
# [translations.fr]
# "results.sortBy.dateStamp" = "Dernière fois que quelqu'un a modifié quelque chose"
#
# Note that translation keys ending with ".html" _can_ contain HTML markup, including inline CSS:
# "catalog.welcome.html" = """
# Welcome to <span class="text-primary">Organization</span>'s<br>
# wonderful <span style="font-size: 1.2em;">data catalogue</span>
# """

[translations.en]
"datahub.header.title.html" = '<div class="text-white">Toutes les <span class="text-primary">données<br>publiques</span> de mon organisation</div>'
