name: Cleanup deployed storybook
on:
  pull_request:
    types: [closed]

jobs:

  storybook-cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "::set-env name=BRANCH_NAME::${GITHUB_HEAD_REF}"
